var weekday=new Array(7);
weekday[0]="Monday";
weekday[1]="Tuesday";
weekday[2]="Wednesday";
weekday[3]="Thursday";
weekday[4]="Friday";
weekday[5]="Saturday";
weekday[6]="Sunday";
console.log("Today is " + weekday[3]);
document.write( weekday[0]+weekday[1]+weekday[2]+weekday[3] +weekday[4]+weekday[5]+weekday[6]+weekday[7]);